id: P003152
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 10:43:49.123717
source_metadata:
  id: bdr:W23171
  title: གསུང་ཐོར་བུ། དཀོན་མཆོག་ཐུབ་བསྟན་བསྟན་པའི་རྒྱལ་མཚན།
  author: ''
  volumes:
    8dcda3584b1e4afa928227fdb47fc12d:
      image_group_id: I0377
      title: ''
      volume_number: 1
      total_pages: 586
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
