id: IF90A0E66
legacy_id: P003152
ocr_import_info:
  bdrc_scan_id: W23171
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T17:31:04'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T00:57:45.540085+00:00'
last_modified: 2022-09-02 08:58:00.392281
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23171
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23171
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་ཐོར་བུ། དཀོན་མཆོག་ཐུབ་བསྟན་བསྟན་པའི་རྒྱལ་མཚན།
  author: ལ་དྭགས་རྟོགས་ལྡན ༠༨་དཀོན་མཆོག་ཐུབ་བསྟན་བསྟན་པའི་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.7700544027565827
  ocr_word_median_confidence_index: 0.9300000071525574
quality: null
bases:
  I0377:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0377
      total_pages: 586
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I0377.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.7700544027565827
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
