id: IF90A0E66
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T17:34:21+00:00'
last_modified: '2022-06-07T17:56:37.933457+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23171
  title: གསུང་ཐོར་བུ། དཀོན་མཆོག་ཐུབ་བསྟན་བསྟན་པའི་རྒྱལ་མཚན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F5C7:
      image_group_id: I0377
      title: ''
      total_pages: 586
      order: 1
      base_file: F5C7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
